[project]
name = "clustering-reddit-posts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "datasets>=4.4.1",
    "nltk>=3.9.2",
    "numpy>=2.3.5",
    "scikit-learn>=1.7.2",
]
